/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useCylinder } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'

useGLTF.preload('/3dmodels/Arrow.glb')

const Arrow = ({ ...props }: any) => {
  const model = useRef()
  const { nodes, materials }: any = useGLTF('/3dmodels/Arrow.glb')

  const [ref] = useCylinder(() => ({
    type: 'Static',
    ...props,
  }))

  return (
    <mesh ref={ref} dispose={null}>
      <group ref={model}>
        <mesh
          scale={[0.3, 0.35, 0.3]}
          geometry={nodes.Cylinder.geometry}
          material={materials['Material.001']}
          position={[0, 0.7, 0]}
          rotation={[Math.PI, 0, 0]}
        />
      </group>
    </mesh>
  )
}
export default Arrow
